---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
#   become_method: sudo
#   become_user: root
#  remote_user: root
  gather_facts: false
  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      ansible.builtin.wait_for_connection:
        timeout: 10 #600
      
    - name: "Check for Python"
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python
      
    - name: "install python for Ansible"
      apt: 
        name: python3.8
        state: present
       
    
  roles:
    - configure-server
    - configure-prometheus-node-exporter
    
#     - install python for Ansible
#     - update/upgrade packages
#     - install nodejs, npm, and pm2
