---
- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/backend-app
    state: directory

- name: "Unarchive backend files "
  unarchive:
     src: artifact.tar.gz
     dest: /home/ubuntu/backend-app 

- name: "Installing Node Dependencies"
  shell: |
     cd /home/ubuntu/backend-app
     npm i 
    
- name: "Executing Node app with PM2"
  args:
       chdir: /home/ubuntu/backend-app/dist
  shell: |
     - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
     - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
     - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
     - TYPEORM_PORT: 5432
     - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
     - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
     - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
     - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
     - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}""
     pm2 stop default
     pm2 start main.js  
  register: execute_node

- name: "Configure pm2 to start as service "
  become: true
  shell: |
    env PATH=${PATH=/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu}
