- name: "upgrade and  update packages"
  become: true
  apt: 
   update_cache: yes
   upgrade: yes
   
   
- name: "remove dependencies that are no longer required"
  apt:
    autoremove: yes


- name: "install nodejs"
  apt:
    name: nodejs
    state: present


- name: "Install pm2 "
  become: yes
  npm:
    name: pm2
    global: yes
    state: present
    production: yes 
    
    
- name:  "create backend directory"
  file:
    path: ~/backend
    state: directory


- name: "Unzip backend files to correct directory"
  unarchive: 
    src: artifact.tar.gz 
    dest: ~/backend

- name: "Install dependencies for project"
  shell: |
    cd ~/backend
    npm install
    
- name: "Check backend files"
  shell: |
    export
    cd ~/backend
    ls -R ~/backend
    
- name: "unarchive backend directory"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "install node dependencies"
  command: npm i 
  args:
    chdir: ~/backend

- name: "install & start app"
  command:  pm2 start main.js
  args:
    chdir: ~/backend/dist
    
  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
